services:
  redis:
    image: redis:latest
    container_name: redis_confx
    platform: linux/amd64
    restart: always
    command: redis-server --requirepass "123456"
    ports:
      - "16379:6379"

  pulsar:
    image: apachepulsar/pulsar:4.1.0
    container_name: pulsar_confx
    platform: linux/amd64
    restart: always
    command: bin/pulsar standalone
    ports:
      - "16650:6650"
      - "18080:8080"

  mysql:
    image: mysql:latest
    container_name: mysql_confx
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: "user"
      MYSQL_PASSWORD: ""
      TZ: "Asia/Shanghai"
    ports:
      - "13306:3306"
    volumes:
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  postgres:
    image: postgres:18
    container_name: postgres_confx
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Shanghai"
    ports:
      - "15432:5432"
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.4.0
    container_name: pulsar_manager_confx
    platform: linux/amd64
    restart: always
    depends_on:
      - pulsar
    ports:
      - "19527:9527" # Web UI
      - "17750:7750" # Manager Backend API
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
      - USERNAME=admin
      - PASSWORD=admin123

  # pulsar-init-helper:
  #   image: curlimages/curl:latest
  #   container_name: pulsar_init_helper_confx
  #   depends_on:
  #     - pulsar
  #     - pulsar-manager
  #   volumes:
  #     - ./pulsar-entrypoint.sh:/pulsar-entrypoint.sh
  #   entrypoint: [ "/bin/sh", "/pulsar-entrypoint.sh" ]

