RUNTIME: STAGING
EXAMPLE__Endpoint_Address: postgres://username:password@hostname:5432/database_name?sslmode=disable
EXAMPLE__Endpoint_Auth_DecryptKeyEnv: PASSWORD_DEC_KEY
EXAMPLE__Endpoint_Auth_Password: ""
EXAMPLE__Endpoint_Auth_Username: ""
EXAMPLE__Endpoint_Cert_CA: ""
EXAMPLE__Endpoint_Cert_Crt: ""
EXAMPLE__Endpoint_Cert_Key: ""
EXAMPLE__WorkerID: 200
